version: '3.7'

services:
  dev:
    image: socket-iface-client:dev
    build:
      context: .
      target: build
    ports: [ '9000:80' ]
    volumes: [ '.:/app' ]
    environment:
      WS_PORT: 3300

  app:
    image: socket-iface-client
    build: .
    init: true
    ports: [ '9000:80' ]
    environment:
      WS_PORT: 3300

  wsproxy:
    image: socket-iface-client/wsproxy
    build: websockify
    ports: [ '3300:3300' ]
    networks: [ websockify ]
    environment:
      TCP_SERVER_HOST: $TCP_SERVER_HOST
      TCP_SERVER_PORT: $TCP_SERVER_PORT

networks:
  websockify:
    name: websockify-proxy
    external: true
